export const skillsDataSet = [
  'Blog Writing',
  'Copywriting',
  'Content Marketing',
  'Technical Writing',
  'Editing and Proofreading',
  'Graphic Design',
  'Web Design',
  'Video Editing',
  'Animation',
  'Illustration',
  'Search Engine Optimization (SEO)',
  'Social Media Marketing',
  'Email Marketing',
  'Pay-Per-Click (PPC) Advertising',
  'Content Strategy',
  'Web Development',
  'Mobile App Development',
  'Front-end Development',
  'Back-end Development',
  'WordPress Development',
  'Data Analysis',
  'Statistical Analysis',
  'Data Visualization',

  'Agile Project Management',
  'Scrum Master',
  'Product Management',
  'Quality Assurance (QA)',
  'Project Scheduling',
  'Administrative Support',
  'Email Management',
  'Calendar Management',
  'Customer Service',
  'Data Entry',
  'Translation Services',
  'Language Teaching',
  'Localization',
  'Transcription',
  'Interpretation',
  'Lead Generation',
  'Sales Funnel Management',
  'Business Strategy',
  'Market Research',
  'Customer Relationship Management (CRM)',
  'Bookkeeping',
  'Accounting',
  'Financial Analysis',
  'Tax Preparation',
  'Budgeting',
  'Audio Editing',
  'Podcast Production',
  'Voice Over',
  'Video Production',
  'Audio Mixing and Mastering',
  'Product Listing and Management',
  'E-commerce Website Development',
  'Inventory Management',
  'Dropshipping Management',
  'Online Store Optimization',
  'Photography',
  'Photo Editing',
  'Photo Retouching',
  'Product Photography',
  'Photo Restoration',
  'Social Media Posting',
  'Community Management',
  'Social Media Analytics',
  'Influencer Outreach',
  'Reputation Management',
  'Legal Research',
  'Contract Review',
  'Intellectual Property (IP) Consulting',
  'Trademark and Copyright Services',
  'Paralegal Services',
  'Fitness Coaching',
  'Nutrition Consulting',
  'Yoga Instruction',
  'Mental Health Counseling',
  'Holistic Health Services',
  'Online Tutoring',
  'Course Development',
  'Educational Content Creation',
  'Test Preparation',
  'Language Instruction',
  'Handmade Crafts',
  'Artistic Creations',
  'Jewelry Making',
  'Custom Clothing Design',
  'Woodworking',
  'Business Consulting',
  'Life Coaching',
  'Career Coaching',
  'Executive Coaching',
  'Leadership Development',
  'IT Support',
  'Helpdesk Support',
  'Network Administration',
  'Cybersecurity',
  'IT Consultation',
].sort();

export const industriesDataSet = [
  'Agriculture',
  'Automotive',
  'Banking and Finance',
  'Construction',
  'Education',
  'Energy',
  'Entertainment',
  'Food and Beverage',
  'Healthcare',
  'Information Technology',
  'Manufacturing',
  'Media and Communications',
  'Retail',
  'Telecommunications',
  'Transportation',
  'Travel and Tourism',
  'Pharmaceuticals',
  'Real Estate',
  'Environmental Services',
  'Aerospace',
  'Biotechnology',
  'Fashion and Apparel',
  'Hospitality',
  'Mining and Minerals',
  'Insurance',
  'Nonprofit and Charity',
  'Sports and Recreation',
  'Public Administration',
].sort();

export const typeOfProjectDataSet = ['Individual', 'Group'].sort();

export const workLocationDataSet = ['On-site', 'Remote', 'Mixed'].sort();

export const sortByDataSet = ['Newest', 'Oldest'].sort();

export const projectStatusDataSet = [
  'Open',
  'Archived',
  'Ongoing',
  'Completed',
].sort();
